### ISSUE TITLE
[BUG] [SP-API] [Issue] `OrderItemId` mismatch between `getOrderItems` and `listFinancialEventsByOrderId` response items

### ISSUE THREAD

**Issue by jamesyanyuk** [amzn/selling-partner-api-docs#2848]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Order items which are presumably identical are returned with different order item IDs. This can be seen by calling both endpoints on a fully shipped order with only a single order item. Both endpoints will return data for order items which seem to match outside of the order item id. This started as of Sun Jan 8, 2023.

## SP-API Name and Version or Report/Feed Type
* Orders: `getOrderItems`
* Finances: `listFinancialEventsByOrderId`

## Expected Behavior

Order items ids should match between items returned by the `getOrderItems` and `listFinancialEventsByOrderId` endpoints in the Orders and Finances APIs, respectively.

## Current Behavior

As of Sun Jan 8, 2023, order item ids returned between the two endpoints no longer match, even for fully shipped orders where it is clear the SKUs line up.

## Context/Screenshots

We are no longer able to accurately match order items returned by the `getOrderItems` endpoint to order items returned by the `listFinancialEventsByOrderId` endpoint.

### Calling `getOrderItems` for an order, A:
```
[
  {
    "AmazonOrderId": "112-1023218-REDACTED-A",
    "SellerOrderId": "112-1023218-REDACTED-A",
    "MarketplaceName": "Amazon.com",
    "PostedDate": "2023-01-07T11:55:00Z",
    "ShipmentItemList": [
      {
        "SellerSKU": "SKU-REDACTED-A",
        "OrderItemId": "41077498237714",
        "QuantityShipped": 1,
        ...
      }
    ]
  }
]
```

### Calling `listFinancialEventsByOrderId` for the same order A:
```
[
  {
    "TaxCollection": {
      "Model": "MarketplaceFacilitator",
      "ResponsibleParty": "Amazon Services, Inc."
    },
    "ProductInfo": {
      "NumberOfItems": "1"
    },
    "BuyerInfo": {},
    "ItemTax": {
      "CurrencyCode": "USD",
      "Amount": "1.58"
    },
    "QuantityShipped": 1,
    "ItemPrice": {
      "CurrencyCode": "USD",
      "Amount": "26.39"
    },
    "ASIN": "ASIN-REDACTED-A",
    "SellerSKU": "SKU-REDACTED-A",
    "Title": "TITLE-REDACTED",
    "IsGift": "false",
    "IsTransparency": false,
    "QuantityOrdered": 1,
    "PromotionDiscountTax": {
      "CurrencyCode": "USD",
      "Amount": "0.00"
    },
    "PromotionDiscount": {
      "CurrencyCode": "USD",
      "Amount": "0.00"
    },
    "OrderItemId": "70167924864721"
  }
]
```

As you can see, with a shipped order and only one item, the SKU matches, but the order item ids no longer match. This becomes a problem for orders with many order items that cannot be matched up with only the SKU (which is a temporary workaround).

**Comment by tomaszhanc** [comment]
@jamesyanyuk hope you are okay with me extending this issue to other APIs to don't duplicate the issue.
Besides what @jamesyanyuk described well. The same problem also occurs between:

## Report with **Orders** vs. Finances API
Reports: `GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL`
Finances: `listFinancialEventsByOrderId`

### Current Behavior
`AmazonOrderItemCode` from the report doesn't match the `OrderAdjustmentItemId` from the Finances API `listFinancialEventsByOrderId` endpoint. Before the bug was introduced, it was always matched. We have been using this for 5+ years (before SP API, with MWS API).

#### `GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL` data
```xml
<Message>
    <Order>
        <AmazonOrderID>111-2704844-0231458</AmazonOrderID>
        <MerchantOrderID>111-2704844-0231458</MerchantOrderID>
        <PurchaseDate>2022-12-31T15:50:45+00:00</PurchaseDate>
        <LastUpdatedDate>2023-01-06T17:44:03+00:00</LastUpdatedDate>
        <OrderStatus>Shipped</OrderStatus>
        <SalesChannel>Amazon.com</SalesChannel>
        <FulfillmentData>
            <FulfillmentChannel>Amazon</FulfillmentChannel>
            <ShipServiceLevel>Expedited</ShipServiceLevel>
            <Address>
                <City>REDACTED</City>
                <State>REDACTED</State>
                <PostalCode>REDACTED</PostalCode>
                <Country>REDACTED</Country>
            </Address>
        </FulfillmentData>
        <IsBusinessOrder>false</IsBusinessOrder>
        <OrderItem>
            <AmazonOrderItemCode>02142901543746</AmazonOrderItemCode>
            <ASIN>B07DKHTKP3</ASIN>
            <SKU>REDACTED</SKU>
            <ItemStatus>Shipped</ItemStatus>
            <ProductName>REDACTED</ProductName>
            <Quantity>2</Quantity>
            <ItemPrice>
                <Component>
                    <Type>Principal</Type>
                    <Amount currency="USD">20.98</Amount>
                </Component>
            </ItemPrice>
        </OrderItem>
    </Order>
</Message>
```

#### Finances API, `listFinancialEventsByOrderId` endpoint data
```json
{
    "AmazonOrderId": "111-2704844-0231458",
    "ShipmentItemAdjustmentList": [
        {
            "SellerSKU": "CA11161-F1010-TX",
            "OrderAdjustmentItemId": "67567655906201",
            "QuantityShipped": 2,
            "ItemChargeAdjustmentList": [
                {
                    "ChargeType": "Tax",
                    "ChargeAmount": {
                        "CurrencyCode": "USD",
                        "CurrencyAmount": -1.19
                    }
                },
                {
                    "ChargeType": "Principal",
                    "ChargeAmount": {
                        "CurrencyCode": "USD",
                        "CurrencyAmount": -19.79
                    }
                }
            ]
        }
    ]
}
```

----

## Report with **Orders** vs. Report with **Fulfilled Shipments**
Reports: `GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL`
Reports: `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL`

### Current Behavior
`AmazonOrderItemCode` from the order report doesn't match `amazon-order-item-id` column from the fulfilled shipments report.

#### `GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL` data
```xml
<Message>
    <Order>
        <AmazonOrderID>111-2704844-0231458</AmazonOrderID>
        <MerchantOrderID>111-2704844-0231458</MerchantOrderID>
        <PurchaseDate>2022-12-31T15:50:45+00:00</PurchaseDate>
        <LastUpdatedDate>2023-01-06T17:44:03+00:00</LastUpdatedDate>
        <OrderStatus>Shipped</OrderStatus>
        <SalesChannel>Amazon.com</SalesChannel>
        <FulfillmentData>
            <FulfillmentChannel>Amazon</FulfillmentChannel>
            <ShipServiceLevel>Expedited</ShipServiceLevel>
            <Address>
                <City>REDACTED</City>
                <State>REDACTED</State>
                <PostalCode>REDACTED</PostalCode>
                <Country>REDACTED</Country>
            </Address>
        </FulfillmentData>
        <IsBusinessOrder>false</IsBusinessOrder>
        <OrderItem>
            <AmazonOrderItemCode>02142901543746</AmazonOrderItemCode>
            <ASIN>B07DKHTKP3</ASIN>
            <SKU>REDACTED</SKU>
            <ItemStatus>Shipped</ItemStatus>
            <ProductName>REDACTED</ProductName>
            <Quantity>2</Quantity>
            <ItemPrice>
                <Component>
                    <Type>Principal</Type>
                    <Amount currency="USD">20.98</Amount>
                </Component>
            </ItemPrice>
        </OrderItem>
    </Order>
</Message>
```

#### `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL` data (simplified)
```TSV
amazon-order-id	merchant-order-id	shipment-id	shipment-item-id	amazon-order-item-id
111-2704844-0231458		TxGvq0lv7	Dt3fdxKTR	61576121866034
```


----

## SP API Status Page

On the status [page](https://sellercentral.amazon.com/sp-api-status):
<img width="764" alt="Screenshot 2023-01-12 at 17 07 14" src="https://user-images.githubusercontent.com/7013293/212119524-7e958951-3ad4-422a-915f-0e2b1c25951b.png">

All the APIs mentioned in this issue (Orders API, Finances API, Reports API) are experiencing some issues now. Is it related to those problems? We would be grateful for more transparency about what you are aware of and currently trying to resolve. Without it, we are blind and don't know what to do ☹️

Similar issues are also raised in https://github.com/amzn/selling-partner-api-docs/discussions/2842 and https://github.com/amzn/selling-partner-api-docs/issues/2836.

**Comment by sungolivia** [comment]
hey @jamesyanyuk @tomaszhanc we have received few reports like you mentioned, if I hear any update regarding this issue, will be posted here as well. Thanks for reporting.

**Comment by tomaszhanc** [comment]
@sungolivia thanks for letting us know, that you are aware of the problem and you are working on resolving this 🙏

**Comment by sungolivia** [comment]
wanted to share that I currently don't have an update but internal team is still working away at this. Hopefully I will come back with some good news in a day or two!

**Comment by tomaszhanc** [comment]
@sungolivia do you have any updates on those issues? Unfortunately, the status page has been updated since Thursday:
<img width="656" alt="Screenshot 2023-01-19 at 10 30 24" src="https://user-images.githubusercontent.com/7013293/213406215-6526589e-b926-4e74-ac26-546eda453d69.png">

**Comment by JeromeXapix** [comment]
hey @sungolivia 

Any update on the issue? Has this been solved?

**Comment by tomaszhanc** [comment]
@sungolivia do you have any ETA for when it will be resolved?

**Comment by rawdrib** [comment]
@sungolivia We are seeing the same behavior and it is breaking our analytics.  Any update on this bug?

**Comment by HardBrick21** [comment]
We are seeing the same behavior in other region Any update on this bug?

**Comment by datamanuco** [comment]
Is there any ETA when it will be fixed? Many thanks.

**Comment by NetRushJacob** [comment]
We've also encountered this, although we only call the Orders\getOrderItems endpoint. Items will come in with one Id, then shift to a different Id later.

Luckily, this hasn't happened (yet) for MFN orders.

**Comment by sungolivia** [comment]
Are you saying that there are new instances of orderIds changing this week? This particular scenario shouldn't be happening anymore but y'all should let me know if you have any new instances!

No ETA I can share at the moment. It's frustrating and appreciate your patience.

**Comment by swexican** [comment]
I can confirm this is still happening, although in our case with MWS API. We noticed that as of February 1, all our financial refund events had started coming in with wrong OrderItemIds. We then found out that even shipment events had been coming in with wrong data for a while. (located in Europe)

**Comment by NetRushJacob** [comment]
> Are you saying that there are new instances of orderIds changing this week? This particular scenario shouldn't be happening anymore but y'all should let me know if you have any new instances!
> 
> No ETA I can share at the moment. It's frustrating and appreciate your patience.

Sorry, I was not clear. We just recently identified the issue in our data, but it was for data through 1/8/2023. To my knowledge, it is not happening beyond that date.  We'll be doing a deeper dive once we adjust our systems to handle this scenario.

**Comment by dazligth** [comment]
Same here, we have a few hundred cases. Didn't saw a specivic one in the past. 
Only many in the sellercentral with an new status "delayed" which I've never seen before.
I assume the "missing"/"delayed" settlement entrys will are available later after a fix with the correct orderItemId.

**Comment by altenschulte** [comment]
same here with the seller-API. First issues startet at 2023-01-31. Since then, there is not a single match between the different endpoints anymore... Still no solution or official statement from amazon?

**Comment by tomaszhanc** [comment]
@sungolivia the [status dashboard](https://sellercentral.amazon.com/sp-api-status) where updated that everything is fine. Does it mean the problem was fixed with historical orders?

**Comment by Toqu-tang** [comment]
Will incorrect historical data be fixed?

**Comment by toniramon** [comment]
SP API seems to be working as red dot dissapeared, still have the issue in MWS

**Comment by dazligth** [comment]
> Will incorrect historical data be fixed?

Jea that's a very important question.

**Comment by altenschulte** [comment]
the financial API still return wrong orderitem-data (since 2023-01-31). Still no fix even though the Seller-API Statuspage says no issues atm.
Anyone else with the problem?

**Comment by mgimena** [comment]
> the financial API still return wrong orderitem-data (since 2023-01-31). Still no fix even though the Seller-API Statuspage says no issues atm.
> Anyone else with the problem?

Yes, we are observing the same thing (see prior post just below yours). And there's no guidance from Amazon about how they have fixed the issue and whether we need to re-fetch orders/finances for specific dates/marketplaces.

**Comment by mgimena** [comment]
> Are you saying that there are new instances of orderIds changing this week? This particular scenario shouldn't be happening anymore but y'all should let me know if you have any new instances!
> 
> No ETA I can share at the moment. It's frustrating and appreciate your patience.

Olivia @sungolivia, this is still happening on SP API, both for EU and NA as of Friday, 17 Feb. 

As you said, it is indeed frustrating when it does not work, but even more so when the Health Dashboard erroneously says the issue is resolved, for everyone to see. This is promoting the wrong expectation to our subscribers who as a consequence of Amazon green-lighting the API endpoints expect us to get this fixed in our system.

**Comment by mgimena** [comment]
@sungolivia Can we please have some guidance about Amazon's intentions on this bug which affects the financial integrity of seller accounts?

The bug was first reported by @HardBrick21 on January 9th (see issue #2836, and again reported by @jamesyanyuk on Jan 11th.

The issue was acknowledged by Amazon on Jan 13th and inexplicably reported as solved on February 16th, without any explanation as to the impact or guidance on what necessary action needs to be taken to rectify the data in local repositories.

As far as we can tell, the issue has NOT been fixed, and data inconsistencies remain.   

Developers are being chastised by their users and are losing professional credibility due to their inability to report on Amazon's plans on the matter. We would be more than happy to assist Amazon in any way we can to get this issue solved finally.

**Comment by RoanOak127** [comment]
@mgimena I'm having the same issue with trying to explain this to our customers. I've built a workaround that's relying on SKU if orderItemId isn't working for our return order processes, but it's not ideal.

Amazon seems to at least acknowledge that they didn't actually fix the problem finally. 

![image](https://user-images.githubusercontent.com/54964349/220362345-04b5fece-141a-4d8f-9e6c-558e69a9d22d.png)

**Comment by tomaszhanc** [comment]
@sungolivia do you have any update on this? If you are not planning to fix it or it's impossible to do so, it's also valuable information. Now, we are all waiting for the fix that may never happen. Well, it's been 6 weeks already. Are you planning to share **the postmortem report** with us so we can understand what happened and why the fix is so hard to implement? It could be a valuable lesson for all of us.

**Comment by swexican** [comment]
> @mgimena I'm having the same issue with trying to explain this to our customers. I've built a workaround that's relying on SKU if orderItemId isn't working for our return order processes, but it's not ideal.
> 
> Amazon seems to at least acknowledge that they didn't actually fix the problem finally.
> 
> ![image](https://user-images.githubusercontent.com/54964349/220362345-04b5fece-141a-4d8f-9e6c-558e69a9d22d.png)

I was hoping to do something similar, but for us the SKU value is empty for those refunds that has a **orderItemId** mismatch, so it doesn't help us. It's becoming a huge problem for us as we generate credit notes based on the finance events data and for some customers we're already a month late!

**Comment by mgimena** [comment]
@dazligth we are also seeing instances of 'Missing' and 'Delayed' statuses for one of our users.

Like you, we have never before seen those statuses, and they are not part of the list of official order statuses in the SP API documentation, as far as we can tell.

Have you by any chance been able to find out what these are and whether they warrant any special action by the seller?

Do these statuses in time ever change to the standard Shipped status, do you know?

**Comment by dazligth** [comment]
In Europe the problem still persits until today (2023-03-21)
Settlement: cOrderItemId from GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING differs from
OrderData: OrderItemCode from GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2

For US my last "broken entry" is from: 2023-01-24 which seems to be back on Track to me. But for US there is another report responsible for orders. In our case GET_AMAZON_FULFILLED_SHIPMENTS_DATA_TAX

**Comment by SB-92** [comment]
Problem still exists. Is there any further development here?

**Comment by DomuITteam** [comment]
Hi, the problem exists for **OrdersV0\ConfirmShipmentRequest** operation. When attempting to confirm any order, API comes back with error 400 response:
```
  "errors": [
    {
      "code": "InvalidInput",
      "message": "OrderItemId  is invalid, please obtain the value through the getOrderItems API or Manage Orders page",
      "details": ""
    }
  ]
```
The **OrderItemId** value is identical in 3 different places - the internal database, **Manage Ordes** page, and **getOrderItems** API response. 

We've tried all 3 in the payload, and compared them in terms of values held and types to confirm they are identical - the error still persists.

**Comment by dazligth** [comment]
Problem still persits for Europe and recently it newly occured in US again in some cases, not in general.

Just one Example: 112-9776753-4807416
![112-9776753-4807416_git](https://user-images.githubusercontent.com/8350749/236451930-796f8655-1fda-494d-95c9-cb703b2ce37a.jpg)

Mismatch between shipping and settlement data like mentioned here:
https://github.com/amzn/selling-partner-api-docs/issues/2848#issuecomment-1477710908

**Comment by jason1004** [comment]
5月1号之后，getOrderItems 再次出现OrderItemID变化的问题

**Comment by LukeLim81** [comment]
Has this recently been fixed around 2 weeks ago for the EU marketplace?

I'm starting to see recent orderItemId starting to match between listFinancialEventsByOrderId and GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL

However, past orderItemId between 30th January to around 16th May are still mismatched

**Comment by bchecketts** [comment]
I found some new data on this. Inside the ItemCustomizationsUrl (for Items that have customizations via [Amazon Custom](https://www.amazon.com/Amazon-Custom/b?ie=UTF8&node=11032013011)), it has an extra field for `LegacyOrderItemId` that contains the value that matches other systems.

So it seems that Amazon "upgraded" something and broke this, and still hasn't produced a way to fix it.

**Comment by 333sec** [comment]
These problems still exist in the JP region.

**Comment by mizio85** [comment]
any updates? to date nothing seems to have been resolved

**Comment by dazligth** [comment]
> any updates? to date nothing seems to have been resolved

OrderItemID seems ressolved, but now the settlement reports are worng in another way.

In V2 settlement report "quantity-purchased" is always empty for "transaction-types" "refunds", so again major problem, because it is not possible to determine how many items the buyer sent back.

**Comment by sagslow** [comment]
OrderItemID  mismatch still happening in some markets, I am using ListFinancialEventsByOrderId:
AU: mismatch 
US:  Not returning any FinacialEvents for ListFinancialEventsByOrderId , but does say issues with APIs on [Health Dashboard ](https://sellercentral.amazon.com/sp-api-status)
EU/AE: Seems to work fine.

So does look like an Aamzon thing....

Kinda worried as MWS is going to die soon....

**Comment by Marina-R** [comment]
We also experience this bug: 
> OrderItemID mismatch still happening in some markets, I am using ListFinancialEventsByOrderId:
> AU: mismatch
