### ISSUE TITLE
Document "InvalidInput" "Invalid Input"

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#343]
I'm not sure where this belongs, but what does "InvalidInput" "Invalid Input" mean?  If I do any POST to /fba/inbound/v0/plans with a body, then the response is:

`{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}`

(If there's no HTTP body then the response is different: `{
  "errors": [
    {
      "code": "InvalidInput",
      "message": " Reason: Country field is missing, Name field is missing, AddressLine1 field is missing.",
      "details": ""
    }
  ]
}
`)

Currently the https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#createinboundshipmentplan documentation doesn't really address 400 errors. It just says "Request has missing or invalid parameters and cannot be parsed."  But, "invalid" in what way?

The API needs to be MUCH more specific regarding what it thinks is "Invalid Input" in that error message.  Perhaps the documentation could get examples as well though.

On a related note, any additional tips on actually getting /fba/inbound/v0/plans to work would be helpful.

**Comment by johnkw** [comment]
After stumbling around randomly trying things I happened on a fix to get past "InvalidInput".  I was using "content-type: application/x-amz-json-1.0" because that's what Amazon's official examples for signing requests used. Apparently SP-API doesn't like that, but it does like "application/json".

I can't find that documented anywhere, but more importantly the API needs to fix that error message to say something like "Invalid Content-Type header - must be application/json"

**Comment by johnkw** [comment]
( It seems likely this was the issue in bug #144 )

**Comment by l20DfX35JnKBfRn** [comment]
Thank you!

**Comment by johnkw** [comment]
Please turn this stupid bot off and resolve the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon @jenilew @parvathm

**Comment by NA-Dev** [comment]
This is still an issue and should not have been closed. This API is not user friendly and support is lacking.

**Comment by AlanParr** [comment]
Just burned a day on this when it could've been easily sorted with a decent error message. Thanks @johnkw for posting your solution, no telling how long I would've been banging my head against the wall before I tried that.

**Comment by cazangabriel** [comment]
how do we up-vote this ??

amazon team, it has been more than 2 years since this has been a problem, how are we supposed to use the API without having access to the actual validation errors on your side ?

any action towards fixing this would be highly appreciated! thanks!

**Comment by johnkw** [comment]
I was told by the API sales team on a marketing survey, that Amazon was migrating off of using github for issue tracking.  The impression I got was that Amazon didn't care about API usability, but the sales person said that was not the reason for the change (but there was no given reason for the change).

**Comment by johnkw** [comment]
Please turn this horrible bot off and only close the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon @jenilew @parvathm

**Comment by pa1983** [comment]
Still a problem - {'code': 'InvalidInput', 'message': 'Invalid Input', 'details': ''} is a total of sod all help.  Currently migrating my old MWS apps over and keep getting stuck in different places with this same 'error'.

**Comment by thyagobr** [comment]
I got some text on "details" section.
Still cryptic, though.
`{"code":"InvalidInput","message":"Invalid input","details":"Provided request is invalid. Please check the request."}`

**Comment by Nizhnikovsky** [comment]
Got the same error on sandbox when try to /feeds/2021-06-30/documents  with 'text/xml; charset=utf-8' or 'application/json; charset=utf-8' contentType. Cretaed only with 'text/tab-separated-values; charset=UTF-8' contentType. But then had and 403 error when try to upload document.
