### ISSUE TITLE
Is "array" in a Type Query parameter always a comma-separated unquoted string?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-docs#356]
This occurs perhaps hundreds of times in the documentation, but see for example ShipmentStatusList in: 
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipments

It says `< enum (ShipmentStatusList) > array` but there's no explanation of how to encode the array. It turns out what it wants is a comma-separated string with no quotation marks. It does NOT allow for an actual URL-encoded JSON array (which is seemingly what the API always uses in the body of a REST call). Also quotation marks are seemingly banned as well, ie the following doesn't work:

`...&QueryType=SHIPMENT&ShipmentStatusList=%27WORKING%27%2C%27SHIPPED%27%2C%27RECEIVING%27%2C%27ERROR%27%2C%27IN_TRANSIT%27`

What it does want is something like:

`...&ShipmentStatusList=WORKING%2CSHIPPED%2CRECEIVING%2CERROR%2CIN_TRANSIT`

Every time the documentation uses the word "array" for a Query, it should link to a section describing what the means. Is it always a comma-separated list? If not, what are the other ways in which an "array" Query is specified?

**Comment by johnkw** [comment]
Also, I didn't mention this explicitly, and maybe it warrants a separate bug, but the use of `,` as the delimiter means these arrays get really bloated with URL-encoding. It sure would be nice to allow space character as a delimiter for example, which could be encoded as a single character `+`.

**Comment by AmericanY** [comment]
@johnkw did you managed on how to send the array ?

i tried that using Python


```
'OrderStatuses[]': ['Shipped', 'Unshipped']
```

**Comment by stefnats** [comment]
@johnkw sorry just a quick guess. have you tried this?

- `...&QueryType=SHIPMENT&ShipmentStatusList[]=WORKING&ShipmentStatusList[]=SHIPPED`
- `...&QueryType=SHIPMENT&ShipmentStatusList=WORKING&ShipmentStatusList=SHIPPED`

**Comment by AmericanY** [comment]
@stefnats 

Just solved it using the following:


```
'OrderStatuses.0': 'Shipped',
'OrderStatuses.1':  'Unshipped'
```

**Comment by stefnats** [comment]
@AmericanY ah right, that pattern looks familiar :)

**Comment by johnkw** [comment]
I don't understand what those comments have to do with this bug. As per my original comment, in python you can do this:

`{'ShipmentStatusList':'WORKING,SHIPPED,RECEIVING,ERROR,IN_TRANSIT'}`

which gets URL-encoded into:

`ShipmentStatusList=WORKING%2CSHIPPED%2CRECEIVING%2CERROR%2CIN_TRANSIT`

This works fine, but as far as I can tell is not documented anywhere. It needs to be documented every time. Ie, every single instance of `< enum (ShipmentStatusList) > array` or similar in the https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipments pages needs to be a link to an explanation of what that field actually IS, and how EXACTLY to construct it.

Also, there's an open question: can anything other than the `,` character can be used? Using pre-encoded `,` is a really wasteful delimiter to choose, being encoded into 3 characters over and over.

**Comment by johnkw** [comment]
I just stumbled on bug #95 where this question was asked previously. It was never answered, and the documentation still needs to address this.

**Comment by johnkw** [comment]
Still broken.

**Comment by Trimakas** [comment]
Yes, this is still an issue.. With Amazon an array isn't an array.. Its so good.. But I have found that you have to send an array like this.. 

`"sku,sku,sku"`

Things to note.. there are no brackets `[]` AND there are no spaces after the commas..

**Comment by syork** [comment]
Considering this goes against the convention with ARRAY parameters it'd be nice if the SP-API at the very least returned an error rather than just seemingly picking the first param. 

Also, please update your documentation. This behavior isn't documented anywhere except random github issues.

**Comment by johnkw** [comment]
Still broken - the original example is now at https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipments but has the exact same problem of not definined the so-called "array".

Please turn this horrible bot off and only close the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon @jenilew @parvathm

**Comment by johnkw** [comment]
I just noticed there are now some inputs, such as on https://developer-docs.amazon.com/sp-api/docs/selling-partner-api-for-a-content-management#getcontentdocument which have a form of
```< enum (IncludedDataSet) > array(csv)```
instead of the original form of:
```< enum (ShipmentStatusList) > array```

The extra "(csv)" on the end seems to be attempting to hint at the fact that this array is indeed a "comma-separated value" string.  It still needs to link to a special documentation page on that.

**Comment by johnkw** [comment]
Please turn this horrible bot off and only close the github tickets as the actual issues are fixed. @adrian-amz @amazon-auto @chapmanjw @amvreddy-amazon @jenilew @parvathm

**Comment by Xriuk** [comment]
This is issue is still very relevant, sad that Amazon doesn't care about addressing it (and many others here)...
