### ISSUE TITLE
REPORT_PROCESSING_FINISHED Notification Type not in Notifications Use Case Guide

### ISSUE THREAD

**Issue by bwhaley-ece** [amzn/selling-partner-api-docs#64]
I noticed that the REPORT_PROCESSING_FINISHED notification is not included in the Notifications Use Case Guide.  It was included in previous versions of the guide, so I wanted to confirm that the SPAPI will support this notification type going forward.  Thanks!

**Comment by codingkondi** [comment]
I have same question about this, thanks

**Comment by seanevan** [comment]
Hi all,

This notification is still included, please see the [notifications model](https://github.com/amzn/selling-partner-api-models/blob/main/models/notifications-api-model/notifications.json). We will seek to clarify this in our documentation.

Best regards,
Sean Evans
Manager, Support Engineering

**Comment by jlevers** [comment]
@seanevan which of the two workflows defined in the Notifications use case guide is used to get `REPORT_PROCESSING_FINISHED` notifications?

**Comment by jlevers** [comment]
For anyone who runs into this question in the future -- I just tested the `REPORT_PROCESSING_FINISHED` notification type with the SQS method described in the Use Case Guide, and was able to make a successful `createSubscription` call.

**Comment by rugved1991** [comment]
Hi @bwhaley-ece,

The documentation has been fixed to reflect the correct [NotificationTypes](https://github.com/amzn/selling-partner-api-docs/blob/main/references/notifications-api/notifications.md#notificationtype). REPORT_PROCESSING_FINISHED and FEED_PROCESSING_FINISHED notification types have been added to the documentation.

Thanks,
Rugved
Solutions Architect, SP API

**Comment by tusbar** [comment]
Hi @rugved1991, the `REPORT_PROCESSING_FINISHED` and `FEED_PROCESSING_FINISHED` are still not present in the [Notifications API Use Case Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/notifications-api-use-case-guide/notifications-use-case-guide-v1.md#notificationtype), which was the point of this issue.

The Notifications API Use Case Guide describes the schema of the notifications, and those notification types are still missing from it.
